version: 0.2

phases:
  pre_build:
    commands:
      - echo "### INIT TERRAFORM"
      - |
        terraform -chdir=terraform init \
          -backend-config="bucket=$S3_BUCKET_ARTIFACT_NAME" \
          -backend-config="key=$S3_BUCKET_ARTIFACT_KEY" \
          -backend-config="dynamodb_table=$DDB_TABLE_NAME" \
          -backend-config="region=$AWS_REGION"

  build:
    commands:
      - echo "### TERRAFORM APPLY"
      - terraform -chdir=terraform apply plan.tfplan --auto-approve
