version: 0.2

phases:
  pre_build:
    commands:
      - echo "### VALIDATE TERRAFORM TEMPLATE"
      - |
        terraform -chdir=terraform init \
          -backend-config="bucket=$S3_BUCKET_ARTIFACT_NAME" \
          -backend-config="key=$S3_BUCKET_ARTIFACT_KEY" \
          -backend-config="dynamodb_table=$DDB_TABLE_NAME" \
          -backend-config="region=$AWS_REGION"
      - terraform -chdir=terraform fmt -recursive
      - terraform -chdir=terraform validate

  build:
    commands:
      - echo "### CREATING LAYERS FOR LAMBDA FUNCTIONS"
      - chmod +x ../scripts/lambda_layer_zipper.sh
      - ../scripts/lambda_layer_zipper.sh

      - echo "### CREATING TERRAFORM PLAN"
      - terraform -chdir=terraform plan -out=plan.tfplan

artifacts:
  name: BuildArtifact
  files:
    - plan.tfplan
