version: 0.2

phases:

  pre_build:
    commands:
      - echo Pre-build phase...
      - sam validate

  build:
    commands:
      - echo Build phase...
      - sam build
      - cfn-lint .aws-sam/build/template.yml

artifacts:
  files:
    - '.aws-sam/build/template.yml'
