version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Install phase...
      - pip3 install cfn-lint

  pre_build:
    commands:
      - echo Pre-build phase...
      - sam validate

  build:
    commands:
      - echo Build phase...
      - sam build
      - ls -la .aws-sam/build
      - cfn-lint .aws-sam/build/template.yml

artifacts:
  files:
    - '.aws-sam/build/template.yml'
