version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Install phase...
      - pip3 install cfn-lint

  pre_build:
    commands:
      - echo Pre-build phase...
      - sam validate

  build:
    commands:
      - echo Build phase...
      - echo Creating layers for Lambda Functions
      - chmod +x ./scripts/lambda_layer_zipper.sh
      - ./scripts/lambda_layer_zipper.sh
      - echo Building SAM Template
      - sam build
      - cfn-lint .aws-sam/build/template.yaml
      - sam package --template-file .aws-sam/build/template.yaml --output-template-file packaged.yaml --s3-bucket ludussma-artifact

artifacts:
  name: BuildArtifact
  files:
    - template.yml
