AWSTemplateFormatVersion: '2010-09-09'

Description: AWS CodePipeline for a Serverless Application

Resources:

  LudusSMALastChatIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: last_chat_id
      Type: String
      Value: "initial_value"  # Change this as necessary
  