AWSTemplateFormatVersion: '2010-09-09'

Description: AWS CodePipeline for a Serverless Application

Conditions:
  Never:
    !Equals [ "A", "B" ]

Resources:

  LudusSMAArtifactS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-unique-bucket-name-123456789
      AccessControl: PublicRead
  