AWSTemplateFormatVersion: '2010-09-09'

Description: AWS CodePipeline for a Serverless Application

Conditions:
  Never:
    !Equals [ "A", "B" ]

Resources:

  NonResource:
    Type: Custom::NonResource
    Condition: Never
  