AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: AWS CodePipeline for a Serverless Application

Parameters:
  TelegramBotKeyParameter:
    Type: String
    Default: /telegram/bot-token
    Description: The key of SSM parameter that contains the Telegram Bot token
  TelegramAllowChatIdsKeyParameter:
    Type: String
    Default: /telegram/allow-chat-ids
    Description: The key of SSM parameter that contains the Telegram allowed chat ids
  TelegramHeaderWebhookTokenKeyParameter:
    Type: String
    Default: /telegram/header-webhook-token
    Description: The key of SSM parameter that contains the Telegram header webhook token
  MetaClientSecretKeyParameter:
    Type: String
    Default: /meta/client-secret
    Description: The key of SSM parameter that contains the Client Secret of Meta Account
  MetaAccessTokenKeyParameter:
    Type: String
    Default: /meta/access-token
    Description: The key of SSM parameter that contains the Access Token of Meta Account    

Resources:

  ### IAM ROLE ###

  LudusSMALambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  
  LudusSMAEventSchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - scheduler.amazonaws.com
            Action:
              - 'sts:AssumeRole'
              
  ### IAM POLICY ###

  LudusSMALambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: LudusSMALambdaPolicy
      Roles:
        - !Ref LudusSMALambdaRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'logs:*'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'dynamodb:GetItem'
              - 'dynamodb:PutItem'
              - 'dynamodb:UpdateItem'           
            Resource: !GetAtt 'LudusSMAChatsHistoryDynamoDBTable.Arn'
          - Effect: Allow
            Action:
              - 'ssm:GetParameter'
            Resource:
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/telegram/*'
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/meta/*'            
          - Effect: Allow
            Action:
              - 'sqs:ReceiveMessage'
              - 'sqs:DeleteMessage' 
              - 'sqs:GetQueueAttributes'             
            Resource:
              - !GetAtt 'LudusSMAEventsSQSQueue.Arn'
              - !GetAtt 'LudusSMATelegramUpdatesSQSQueue.Arn'
          - Effect: Allow
            Action:
              - 'sqs:SendMessage'
            Resource: !GetAtt 'LudusSMATelegramUpdatesSQSQueue.Arn'
          - Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:ListBucket'
              - 's3:ListObjects'
            Resource:
              - !GetAtt 'LudusSMAImagesBucket.Arn'
              - !Sub '${LudusSMAImagesBucket.Arn}/*'
              - !GetAtt 'LudusSMAChatPersistenceBucket.Arn'
              - !Sub '${LudusSMAChatPersistenceBucket.Arn}/*'
          - Effect: Allow
            Action:
              - 'scheduler:CreateSchedule'
            Resource: !Sub 'arn:aws:scheduler:${AWS::Region}:${AWS::AccountId}:schedule/*'
          - Effect: Allow
            Action:
              - 'iam:PassRole'
            Resource: !GetAtt 'LudusSMAEventSchedulerRole.Arn'
          - Effect: Allow
            Action:
              - 'bedrock:InvokeModel'
            Resource: 'arn:aws:bedrock:*'

  LudusSMAEventSchedulerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: LudusSMASchedulerPolicy
      Roles:
        - !Ref LudusSMAEventSchedulerRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'sqs:SendMessage'
            Resource: !GetAtt 'LudusSMAEventsSQSQueue.Arn'

  ### PARAMETER ###

  # Parameters cannot be created by Cloud Formation if they are of type SecureString
  # which is why they were created by hand inside the console
  # parameter keys are passed within the Lambda Function as environment variables.

  ### S3 BUCKET ###

  LudusSMAImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ludussma-images
      VersioningConfiguration:
        Status: Enabled
  
  LudusSMAChatPersistenceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ludussma-chat-persistence
      VersioningConfiguration:
        Status: Enabled

  ### DYNAMODB TABLES ###

  LudusSMAChatsHistoryDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      DeletionProtectionEnabled: true
      TableName: ChatsHistory
      TableClass: STANDARD
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH

### SQS QUEUE ###

  LudusSMAEventsSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ScheduledEvents
      VisibilityTimeout: 300

  LudusSMATelegramUpdatesSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: TelegramUpdates
      VisibilityTimeout: 300
        
### LAMBDA FUNCTIONS ###

  LudusSMAAuthTgRequestsFunction:
    Type: AWS::Serverless::Function    
    Name: auth-tg-requests
    Properties:
      CodeUri: lambda_auth_tg_requests/
      Handler: main.lambda_handler
      Runtime: python3.11
      Timeout: 60
      Architectures:
        - x86_64
      Role: !GetAtt LudusSMALambdaRole.Arn
      Environment:
        Variables:
          TELEGRAM_HEADER_WEBHOOK_TOKEN: !Ref TelegramHeaderWebhookTokenKeyParameter
          SQS_QUEUE_TELEGRAM_UPDATES_NAME: !GetAtt LudusSMATelegramUpdatesSQSQueue.QueueName
      Layers:
        - !Ref LudusSMALambdaLayer
      Events:
        TelegramUpdateHandler:
          Type: Api
          Properties:
            Path: /telegram-bot
            Method: post

  LudusSMATelegramBotFunction:
    Type: AWS::Serverless::Function
    Name: telegram-bot
    Properties:
      CodeUri: lambda_telegram_bot/
      Handler: main.lambda_handler
      Runtime: python3.11
      Timeout: 300
      MemorySize: 512
      Architectures:
        - x86_64
      Role: !GetAtt LudusSMALambdaRole.Arn
      Environment:
        Variables:
          TELEGRAM_BOT_KEY: !Ref TelegramBotKeyParameter
          TELEGRAM_ALLOW_CHAT_IDS: !Ref TelegramAllowChatIdsKeyParameter
          SQS_QUEUE_TELEGRAM_UPDATES_NAME: !GetAtt LudusSMATelegramUpdatesSQSQueue.QueueName
          SQS_QUEUE_EVENTS_ARN: !GetAtt LudusSMAEventsSQSQueue.Arn
          DYNAMODB_TABLE_CHATS_HISTORY_NAME: !Ref LudusSMAChatsHistoryDynamoDBTable
          IAM_ROLE_EVENT_SCHEDULER_ARN: !GetAtt LudusSMAEventSchedulerRole.Arn
          S3_BUCKET_IMAGES_NAME: !Ref LudusSMAImagesBucket
          S3_BUCKET_CHAT_PERSISTENCE_NAME: !Ref LudusSMAChatPersistenceBucket
      Layers:
        - !Ref LudusSMALambdaLayer
      Events:
        TelegramUpdateHandler:
          Type: SQS
          Properties:
            Queue: !GetAtt LudusSMATelegramUpdatesSQSQueue.Arn
            BatchSize: 1

  LudusSMACreateIGStoriesFunction:
    Type: AWS::Serverless::Function
    Name: create-ig-stories
    Properties:
      CodeUri: lambda_create_ig_stories/
      Handler: main.lambda_handler
      Runtime: python3.11
      Timeout: 300
      MemorySize: 512
      Architectures:
        - x86_64
      Role: !GetAtt LudusSMALambdaRole.Arn
      Environment:
        Variables:
          META_CLIENT_SECRET: !Ref MetaClientSecretKeyParameter
          META_ACCESS_TOKEN: !Ref MetaAccessTokenKeyParameter
      Layers:
        - !Ref LudusSMALambdaLayer
      Events:
        ScheduledEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt LudusSMAEventsSQSQueue.Arn
            BatchSize: 1      

### LAMBDA LAYER ###

  LudusSMALambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Name: lambda-utils-layer
    Properties:
      LayerName: LudusSMAUtilsLayer
      Description: LudusSMA Utils Lambda Layer
      ContentUri: utils.zip
      CompatibleRuntimes:
        - python3.11

