AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: AWS CodePipeline for a Serverless Application

Resources:

  ### IAM ROLE ###

  LudusSMALambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
              
  ### IAM POLICY ###

  LudusSMALambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: LudusSMALambdaPolicy
      Roles:
        - !Ref LudusSMALambdaRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'logs:*'
              - 'dynamodb:*'              
              - 'events:*'
              - 'sqs:*'
              - 'systemsmanager:*'
            Resource: '*'

  ### PARAMETER ###

  # Parameters cannot be created by Cloud Formation if they are of type SecureString
  # which is why they were created by hand inside the console
  # TODO: add a build step to create these parameters
  
  ### SECRET ###

  LudusSMAMetaCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: meta-credentials
      Description: Credential for Meta Account      
      SecretString: initial_value
  
  LudusSMAImgurCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: imgur-credentials
      Description: Credential for Imgur Account
      SecretString: initial_value

  ### DYNAMODB TABLES ###

  LudusSMAChatsHistoryDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      DeletionProtectionEnabled: true
      TableName: ChatsHistory
      TableClass: STANDARD
      AttributeDefinitions:
        - AttributeName: chat_id
          AttributeType: S
        - AttributeName: message_timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: chat_id
          KeyType: HASH
        - AttributeName: message_timestamp
          KeyType: RANGE

  LudusSMAUserLastChatIDDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      DeletionProtectionEnabled: true
      TableName: UserLastChatID
      TableClass: STANDARD
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH

  LudusSMAEventsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      DeletionProtectionEnabled: true
      TableName: Events
      TableClass: STANDARD
      AttributeDefinitions:
        - AttributeName: event_id
          AttributeType: S
      KeySchema:
        - AttributeName: event_id
          KeyType: HASH
        
### LAMBDA FUNCTIONS ###

  LudusSMATelegramBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/telegram_bot/
      Handler: main.lambda_handler
      Runtime: python3.11
      Timeout: 300
      MemorySize: 1024
      Architectures:
        - x86_64
      Role: !GetAtt LudusSMALambdaRole.Arn
      Layers:
        - !Ref LudusSMALambdaLayer
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /telegram-bot
            Method: post

### LAMBDA LAYER ###

  LudusSMALambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: LudusSMAUtilsLayer
      Description: LudusSMA Utils Lambda Layer
      ContentUri: lambda_functions/utils.zip
      CompatibleRuntimes:
        - python3.11

